Fixed separate_independent_conditional to correctly handle q_sqrt=None.
Previously if q_sqrt=None the method would fail with
AttributeError: 'NoneType' object has no attribute 'shape'.

Added if statement to check is q_sqrt is None.
If q_sqrt=None, method does not attempt to transpose q_sqrt and
map it through single_gp_conditional.