Update svi_test.ipynb (#361)
To avoid a `TypeError: _optimize_tf() got an unexpected keyword argument 'max_iters'`, `max_iters` needs to be replaced by `maxiter`