Update svi_test.ipynb
To avoid a `TypeError: _optimize_tf() got an unexpected keyword argument 'max_iters'`, `max_iters` needs to be replaced by `maxiter`